Move tools locally
Osekai/osekai pull request #224
Opened 2023-01-12 12:48 UTC by Tanza3D

2023-01-12 16:34 UTC, minusQuantumNeko requested changes

2023-01-12 16:34 UTC, minusQuantumNeko commented on tools/src/stdev_pp_calc/README.md
> +owners-github: remryia
Bro xD
```suggestion
owners-github: remyria
```

2023-01-12 16:51 UTC, Tanza3D commented on tools/src/stdev_pp_calc/README.md
> +owners-github: remryia
remryia

2023-01-12 16:53 UTC, minusQuantumNeko submitted a review, later dismissed
Fix CODEOWNERS, but everything else should be okay

2023-01-15 00:54 UTC, EXtremeExploit approved these changes
ok ig, i want input from @minusQuantumNeko to know if his tool is up to date just to be sure

2023-01-15 00:55 UTC, Tanza3D commented
can tell u now it probably is, looks up to date to me

2023-01-15 00:56 UTC, minusQuantumNeko commented
I think it is @EXtremeExploit

2023-01-15 00:56 UTC, merged

2023-01-15 00:57 UTC, minusQuantumNeko approved these changes