Add contributing guidelines and format every js file
Osekai/osekai pull request #69
Opened 2022-11-30 21:41 UTC by EXtremeExploit

literally title, now with contributing guidelines i think there should be some rules to follow or to at least have A BIT of code quality check. still a work in progress as i still have to add the workflow that checks for each push and actually format all files acording to .eslintrc. @Tanza3D @mulraf if you guys feel like adding any comments on what rules should follow i'll gladly accept them. there are some that are impossible like functions or variables not being used as they may be used in other files, using of undefined variables has to be added manually to the `globals` section of the .eslintrc, i think it also helps to keep track of every global so its fine. thankfully there aren't that many globals (i think)

same goes for the contrib guidelines please i want feedback

2022-11-30 22:03 UTC, minusQuantumNeko requested changes

2022-11-30 22:03 UTC, minusQuantumNeko commented on CONTRIBUTING.md
> +* Must pass all tests
```suggestion
* **Must** pass all [checks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks)!
```

2022-11-30 22:03 UTC, minusQuantumNeko commented on CONTRIBUTING.md
> +* Source branch **MUST NOT** be `main`
```suggestion
* Source branch **MUST __NOT__** be `main`!
```

2022-11-30 22:03 UTC, minusQuantumNeko commented on CONTRIBUTING.md
> +* Destination branch should be `main`
```suggestion
* Destination branch **must** be `main`!
```

2022-11-30 22:03 UTC, minusQuantumNeko commented on CONTRIBUTING.md
> +* All JS code must be formatted according to `.eslintrc` rules.
```suggestion
* All **`JS`** code **must** be formatted according to `.eslintrc` rules.
```

2022-11-30 22:08 UTC, Tanza3D commented on CONTRIBUTING.md
> +### If you don't want to or not know how to contribute code:
i think this is more an option for people who also don't know how to code, a better choice might be:
`If you don't want to, or do not know how to code or contribute your code`

2022-11-30 22:08 UTC, EXtremeExploit commented on CONTRIBUTING.md
> +### If you don't want to or not know how to contribute code:
i mean not know how to contribute code as if you don't know how to code, i guess i can reword this as `I don't feel confident enough in my experience in coding D: What can i do?`?

2022-11-30 22:09 UTC, minusQuantumNeko commented on CONTRIBUTING.md
> +### If you don't want to or not know how to contribute code:
> i think this is more an option for people who also don't know how to code, a better choice might be: `If you don't want to, or do not know how to code or contribute your code`

Updated suggestion

2022-11-30 22:19 UTC, EXtremeExploit commented on CONTRIBUTING.md
> +
honestly i have mixed feelings about this one, i agree that it is good to have it, but only make use of it for stuff like fixing stuff right before merge that is impossible to have the guy making the pr have any objections about it or if the PR is dead but easy to pickup. I don't know about you guys but at least thats how i see it, i do still think that code changes made this way have to be reviewed by the guy making the pr too. i don't know how to put this in the guidelines or if you guys agree. just my opinion

2022-12-01 22:52 UTC, Tanza3D commented on CONTRIBUTING.md
> +
i don't see the point in having this honestly

2022-12-01 22:52 UTC, minusQuantumNeko commented on CONTRIBUTING.md
> +
Honestly, it doesn't harm to have that, better to have that when we need it than not. Also even osu-wiki says that if I remember correctly

2022-12-01 22:52 UTC, Tanza3D commented on CONTRIBUTING.md
> +
i guessss

2022-12-01 22:53 UTC, EXtremeExploit commented on CONTRIBUTING.md
> +
now that i think about it we can put it as recommended :thinking: . just a suggestion

2022-12-01 22:53 UTC, minusQuantumNeko commented on CONTRIBUTING.md
> +
But what does it change, lol?

2022-12-10 12:47 UTC, Tanza3D commented
is css class name guidelines doable?

2023-05-11 18:07 UTC, closed without merging